### ISSUE TITLE
Image doesn't update if tag is the same

### ISSUE THREAD

**Issue by thebongy** [csivitu/ctfup#10]
Currently, image updates are not being applied as the tag name applied is always latest. An alternative is to take the SHA Hash of the current commit, and use that as a tag while building instead.

Or, maybe we can just specify (imagePullPolicy: Always) to force a pull on every patch

**Comment by roerohan** [comment]
@thebongy should be fixed.
The container uses the latest has from the `getHash()` function in `command.ts`.
